outfile:main.o Add_new_record.o print.o Delete_a_record.o Show_the_list.o Reverse_the_list.o Sort_the_list.o Modify_a_record.o Save.o Delete_all_the_records.o
	cc main.c Add_new_record.c print.c Delete_a_record.c Show_the_list.c Reverse_the_list.c Sort_the_list.c Modify_a_record.c Save.o Delete_all_the_records.c -o outfile
main.o:main.c
	cc -c main.c
Add_new_record.o:Add_new_record.c
	cc -c Add_new_record.c
print.o:print.c
	cc -c print.c
Delete_a_record.o:Delete_a_record.c
	cc -c Delete_a_record.c
Show_the_list.o:Show_the_list.c
	cc -c Show_the_list.c
Reverse_the_list.o:Reverse_the_list.c
	cc -c Reverse_the_list.c
Sort_the_list.o:Sort_the_list.c
	cc -c Sort_the_list.c
Modify_a_record.o:Modify_a_record.c
	cc -c Modify_a_record.c
Save.o:Save.c
	cc -c Save.c
Delete_all_the_records.o:Delete_all_the_records.c
	cc -c Delete_all_the_records.c


